name: Build PurpleKEY

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: PurpleKEY-linux
            icon: purplekey_icon.png
          - os: windows-latest
            name: PurpleKEY-windows.exe
            icon: purplekey_icon.ico
          - os: macos-latest
            name: PurpleKEY-macos
            icon: purplekey_icon.icns

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Compiler
        run: >
          pyinstaller --onefile --windowed
          --name ${{ matrix.name }}
          --icon ${{ matrix.icon }}
          main.py

      - name: Créer la Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.name }}
